// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/StasMerzlyakov/gophkeeper/internal/server/usecases (interfaces: StateFullStorage,TemporaryStorage,EMailSender,RegistrationHelper,FileStorage)

// Package usecases_test is a generated GoMock package.
package usecases_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/StasMerzlyakov/gophkeeper/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockStateFullStorage is a mock of StateFullStorage interface.
type MockStateFullStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStateFullStorageMockRecorder
}

// MockStateFullStorageMockRecorder is the mock recorder for MockStateFullStorage.
type MockStateFullStorageMockRecorder struct {
	mock *MockStateFullStorage
}

// NewMockStateFullStorage creates a new mock instance.
func NewMockStateFullStorage(ctrl *gomock.Controller) *MockStateFullStorage {
	mock := &MockStateFullStorage{ctrl: ctrl}
	mock.recorder = &MockStateFullStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateFullStorage) EXPECT() *MockStateFullStorageMockRecorder {
	return m.recorder
}

// CreateBankCard mocks base method.
func (m *MockStateFullStorage) CreateBankCard(arg0 context.Context, arg1 *domain.EncryptedBankCard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankCard", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBankCard indicates an expected call of CreateBankCard.
func (mr *MockStateFullStorageMockRecorder) CreateBankCard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankCard", reflect.TypeOf((*MockStateFullStorage)(nil).CreateBankCard), arg0, arg1)
}

// CreateUserPasswordData mocks base method.
func (m *MockStateFullStorage) CreateUserPasswordData(arg0 context.Context, arg1 *domain.EncryptedUserPasswordData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserPasswordData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserPasswordData indicates an expected call of CreateUserPasswordData.
func (mr *MockStateFullStorageMockRecorder) CreateUserPasswordData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserPasswordData", reflect.TypeOf((*MockStateFullStorage)(nil).CreateUserPasswordData), arg0, arg1)
}

// DeleteBankCard mocks base method.
func (m *MockStateFullStorage) DeleteBankCard(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBankCard", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBankCard indicates an expected call of DeleteBankCard.
func (mr *MockStateFullStorageMockRecorder) DeleteBankCard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBankCard", reflect.TypeOf((*MockStateFullStorage)(nil).DeleteBankCard), arg0, arg1)
}

// DeleteUserPasswordData mocks base method.
func (m *MockStateFullStorage) DeleteUserPasswordData(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserPasswordData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserPasswordData indicates an expected call of DeleteUserPasswordData.
func (mr *MockStateFullStorageMockRecorder) DeleteUserPasswordData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserPasswordData", reflect.TypeOf((*MockStateFullStorage)(nil).DeleteUserPasswordData), arg0, arg1)
}

// GetBankCardList mocks base method.
func (m *MockStateFullStorage) GetBankCardList(arg0 context.Context) ([]domain.EncryptedBankCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankCardList", arg0)
	ret0, _ := ret[0].([]domain.EncryptedBankCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankCardList indicates an expected call of GetBankCardList.
func (mr *MockStateFullStorageMockRecorder) GetBankCardList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankCardList", reflect.TypeOf((*MockStateFullStorage)(nil).GetBankCardList), arg0)
}

// GetHelloData mocks base method.
func (m *MockStateFullStorage) GetHelloData(arg0 context.Context) (*domain.HelloData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHelloData", arg0)
	ret0, _ := ret[0].(*domain.HelloData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHelloData indicates an expected call of GetHelloData.
func (mr *MockStateFullStorageMockRecorder) GetHelloData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelloData", reflect.TypeOf((*MockStateFullStorage)(nil).GetHelloData), arg0)
}

// GetLoginData mocks base method.
func (m *MockStateFullStorage) GetLoginData(arg0 context.Context, arg1 string) (*domain.LoginData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginData", arg0, arg1)
	ret0, _ := ret[0].(*domain.LoginData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginData indicates an expected call of GetLoginData.
func (mr *MockStateFullStorageMockRecorder) GetLoginData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginData", reflect.TypeOf((*MockStateFullStorage)(nil).GetLoginData), arg0, arg1)
}

// GetUserFilesBucket mocks base method.
func (m *MockStateFullStorage) GetUserFilesBucket(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFilesBucket", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFilesBucket indicates an expected call of GetUserFilesBucket.
func (mr *MockStateFullStorageMockRecorder) GetUserFilesBucket(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFilesBucket", reflect.TypeOf((*MockStateFullStorage)(nil).GetUserFilesBucket), arg0)
}

// GetUserPasswordDataList mocks base method.
func (m *MockStateFullStorage) GetUserPasswordDataList(arg0 context.Context) ([]domain.EncryptedUserPasswordData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPasswordDataList", arg0)
	ret0, _ := ret[0].([]domain.EncryptedUserPasswordData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPasswordDataList indicates an expected call of GetUserPasswordDataList.
func (mr *MockStateFullStorageMockRecorder) GetUserPasswordDataList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPasswordDataList", reflect.TypeOf((*MockStateFullStorage)(nil).GetUserPasswordDataList), arg0)
}

// IsEMailAvailable mocks base method.
func (m *MockStateFullStorage) IsEMailAvailable(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEMailAvailable", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEMailAvailable indicates an expected call of IsEMailAvailable.
func (mr *MockStateFullStorageMockRecorder) IsEMailAvailable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEMailAvailable", reflect.TypeOf((*MockStateFullStorage)(nil).IsEMailAvailable), arg0, arg1)
}

// Registrate mocks base method.
func (m *MockStateFullStorage) Registrate(arg0 context.Context, arg1 *domain.FullRegistrationData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Registrate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Registrate indicates an expected call of Registrate.
func (mr *MockStateFullStorageMockRecorder) Registrate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Registrate", reflect.TypeOf((*MockStateFullStorage)(nil).Registrate), arg0, arg1)
}

// UpdateBankCard mocks base method.
func (m *MockStateFullStorage) UpdateBankCard(arg0 context.Context, arg1 *domain.EncryptedBankCard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBankCard", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBankCard indicates an expected call of UpdateBankCard.
func (mr *MockStateFullStorageMockRecorder) UpdateBankCard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBankCard", reflect.TypeOf((*MockStateFullStorage)(nil).UpdateBankCard), arg0, arg1)
}

// UpdateUserPasswordData mocks base method.
func (m *MockStateFullStorage) UpdateUserPasswordData(arg0 context.Context, arg1 *domain.EncryptedUserPasswordData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPasswordData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPasswordData indicates an expected call of UpdateUserPasswordData.
func (mr *MockStateFullStorageMockRecorder) UpdateUserPasswordData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPasswordData", reflect.TypeOf((*MockStateFullStorage)(nil).UpdateUserPasswordData), arg0, arg1)
}

// MockTemporaryStorage is a mock of TemporaryStorage interface.
type MockTemporaryStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTemporaryStorageMockRecorder
}

// MockTemporaryStorageMockRecorder is the mock recorder for MockTemporaryStorage.
type MockTemporaryStorageMockRecorder struct {
	mock *MockTemporaryStorage
}

// NewMockTemporaryStorage creates a new mock instance.
func NewMockTemporaryStorage(ctrl *gomock.Controller) *MockTemporaryStorage {
	mock := &MockTemporaryStorage{ctrl: ctrl}
	mock.recorder = &MockTemporaryStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemporaryStorage) EXPECT() *MockTemporaryStorageMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTemporaryStorage) Create(arg0 context.Context, arg1 domain.SessionID, arg2 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTemporaryStorageMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTemporaryStorage)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockTemporaryStorage) Delete(arg0 context.Context, arg1 domain.SessionID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", arg0, arg1)
}

// Delete indicates an expected call of Delete.
func (mr *MockTemporaryStorageMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTemporaryStorage)(nil).Delete), arg0, arg1)
}

// DeleteAndCreate mocks base method.
func (m *MockTemporaryStorage) DeleteAndCreate(arg0 context.Context, arg1, arg2 domain.SessionID, arg3 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAndCreate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAndCreate indicates an expected call of DeleteAndCreate.
func (mr *MockTemporaryStorageMockRecorder) DeleteAndCreate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAndCreate", reflect.TypeOf((*MockTemporaryStorage)(nil).DeleteAndCreate), arg0, arg1, arg2, arg3)
}

// Load mocks base method.
func (m *MockTemporaryStorage) Load(arg0 context.Context, arg1 domain.SessionID) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockTemporaryStorageMockRecorder) Load(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockTemporaryStorage)(nil).Load), arg0, arg1)
}

// LoadAndDelete mocks base method.
func (m *MockTemporaryStorage) LoadAndDelete(arg0 context.Context, arg1 domain.SessionID) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAndDelete", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAndDelete indicates an expected call of LoadAndDelete.
func (mr *MockTemporaryStorageMockRecorder) LoadAndDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAndDelete", reflect.TypeOf((*MockTemporaryStorage)(nil).LoadAndDelete), arg0, arg1)
}

// MockEMailSender is a mock of EMailSender interface.
type MockEMailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEMailSenderMockRecorder
}

// MockEMailSenderMockRecorder is the mock recorder for MockEMailSender.
type MockEMailSenderMockRecorder struct {
	mock *MockEMailSender
}

// NewMockEMailSender creates a new mock instance.
func NewMockEMailSender(ctrl *gomock.Controller) *MockEMailSender {
	mock := &MockEMailSender{ctrl: ctrl}
	mock.recorder = &MockEMailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEMailSender) EXPECT() *MockEMailSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockEMailSender) Send(arg0 context.Context, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEMailSenderMockRecorder) Send(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEMailSender)(nil).Send), arg0, arg1, arg2)
}

// MockRegistrationHelper is a mock of RegistrationHelper interface.
type MockRegistrationHelper struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationHelperMockRecorder
}

// MockRegistrationHelperMockRecorder is the mock recorder for MockRegistrationHelper.
type MockRegistrationHelperMockRecorder struct {
	mock *MockRegistrationHelper
}

// NewMockRegistrationHelper creates a new mock instance.
func NewMockRegistrationHelper(ctrl *gomock.Controller) *MockRegistrationHelper {
	mock := &MockRegistrationHelper{ctrl: ctrl}
	mock.recorder = &MockRegistrationHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationHelper) EXPECT() *MockRegistrationHelperMockRecorder {
	return m.recorder
}

// CheckEMailData mocks base method.
func (m *MockRegistrationHelper) CheckEMailData(arg0 *domain.EMailData) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEMailData", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckEMailData indicates an expected call of CheckEMailData.
func (mr *MockRegistrationHelperMockRecorder) CheckEMailData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEMailData", reflect.TypeOf((*MockRegistrationHelper)(nil).CheckEMailData), arg0)
}

// CreateJWTToken mocks base method.
func (m *MockRegistrationHelper) CreateJWTToken(arg0 domain.UserID) (domain.JWTToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJWTToken", arg0)
	ret0, _ := ret[0].(domain.JWTToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJWTToken indicates an expected call of CreateJWTToken.
func (mr *MockRegistrationHelperMockRecorder) CreateJWTToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJWTToken", reflect.TypeOf((*MockRegistrationHelper)(nil).CreateJWTToken), arg0)
}

// DecryptOTPKey mocks base method.
func (m *MockRegistrationHelper) DecryptOTPKey(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptOTPKey", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptOTPKey indicates an expected call of DecryptOTPKey.
func (mr *MockRegistrationHelperMockRecorder) DecryptOTPKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptOTPKey", reflect.TypeOf((*MockRegistrationHelper)(nil).DecryptOTPKey), arg0)
}

// EncryptOTPKey mocks base method.
func (m *MockRegistrationHelper) EncryptOTPKey(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptOTPKey", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptOTPKey indicates an expected call of EncryptOTPKey.
func (mr *MockRegistrationHelperMockRecorder) EncryptOTPKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptOTPKey", reflect.TypeOf((*MockRegistrationHelper)(nil).EncryptOTPKey), arg0)
}

// GenerateQR mocks base method.
func (m *MockRegistrationHelper) GenerateQR(arg0 string) (string, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateQR", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateQR indicates an expected call of GenerateQR.
func (mr *MockRegistrationHelperMockRecorder) GenerateQR(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateQR", reflect.TypeOf((*MockRegistrationHelper)(nil).GenerateQR), arg0)
}

// HashPassword mocks base method.
func (m *MockRegistrationHelper) HashPassword(arg0 string) (*domain.HashData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", arg0)
	ret0, _ := ret[0].(*domain.HashData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockRegistrationHelperMockRecorder) HashPassword(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockRegistrationHelper)(nil).HashPassword), arg0)
}

// NewSessionID mocks base method.
func (m *MockRegistrationHelper) NewSessionID() domain.SessionID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSessionID")
	ret0, _ := ret[0].(domain.SessionID)
	return ret0
}

// NewSessionID indicates an expected call of NewSessionID.
func (mr *MockRegistrationHelperMockRecorder) NewSessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSessionID", reflect.TypeOf((*MockRegistrationHelper)(nil).NewSessionID))
}

// ParseJWTToken mocks base method.
func (m *MockRegistrationHelper) ParseJWTToken(arg0 domain.JWTToken) (domain.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseJWTToken", arg0)
	ret0, _ := ret[0].(domain.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseJWTToken indicates an expected call of ParseJWTToken.
func (mr *MockRegistrationHelperMockRecorder) ParseJWTToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseJWTToken", reflect.TypeOf((*MockRegistrationHelper)(nil).ParseJWTToken), arg0)
}

// ValidateAccountPass mocks base method.
func (m *MockRegistrationHelper) ValidateAccountPass(arg0, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccountPass", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccountPass indicates an expected call of ValidateAccountPass.
func (mr *MockRegistrationHelperMockRecorder) ValidateAccountPass(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccountPass", reflect.TypeOf((*MockRegistrationHelper)(nil).ValidateAccountPass), arg0, arg1, arg2)
}

// ValidateOTPCode mocks base method.
func (m *MockRegistrationHelper) ValidateOTPCode(arg0, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateOTPCode", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateOTPCode indicates an expected call of ValidateOTPCode.
func (mr *MockRegistrationHelperMockRecorder) ValidateOTPCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateOTPCode", reflect.TypeOf((*MockRegistrationHelper)(nil).ValidateOTPCode), arg0, arg1)
}

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// CreateStreamFileWriter mocks base method.
func (m *MockFileStorage) CreateStreamFileWriter(arg0 context.Context, arg1 string) (domain.StreamFileWriter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStreamFileWriter", arg0, arg1)
	ret0, _ := ret[0].(domain.StreamFileWriter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStreamFileWriter indicates an expected call of CreateStreamFileWriter.
func (mr *MockFileStorageMockRecorder) CreateStreamFileWriter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStreamFileWriter", reflect.TypeOf((*MockFileStorage)(nil).CreateStreamFileWriter), arg0, arg1)
}

// DeleteFileInfo mocks base method.
func (m *MockFileStorage) DeleteFileInfo(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFileInfo indicates an expected call of DeleteFileInfo.
func (mr *MockFileStorageMockRecorder) DeleteFileInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileInfo", reflect.TypeOf((*MockFileStorage)(nil).DeleteFileInfo), arg0, arg1, arg2)
}

// GetFileInfoList mocks base method.
func (m *MockFileStorage) GetFileInfoList(arg0 context.Context, arg1 string) ([]domain.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileInfoList", arg0, arg1)
	ret0, _ := ret[0].([]domain.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileInfoList indicates an expected call of GetFileInfoList.
func (mr *MockFileStorageMockRecorder) GetFileInfoList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileInfoList", reflect.TypeOf((*MockFileStorage)(nil).GetFileInfoList), arg0, arg1)
}
