// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/StasMerzlyakov/gophkeeper/internal/domain (interfaces: Logger,StreamFileWriter,StreamFileReader)

// Package domain_test is a generated GoMock package.
package domain_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debugw mocks base method.
func (m *MockLogger) Debugw(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugw", varargs...)
}

// Debugw indicates an expected call of Debugw.
func (mr *MockLoggerMockRecorder) Debugw(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugw", reflect.TypeOf((*MockLogger)(nil).Debugw), varargs...)
}

// Errorw mocks base method.
func (m *MockLogger) Errorw(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorw", varargs...)
}

// Errorw indicates an expected call of Errorw.
func (mr *MockLoggerMockRecorder) Errorw(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorw", reflect.TypeOf((*MockLogger)(nil).Errorw), varargs...)
}

// Infow mocks base method.
func (m *MockLogger) Infow(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infow", varargs...)
}

// Infow indicates an expected call of Infow.
func (mr *MockLoggerMockRecorder) Infow(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infow", reflect.TypeOf((*MockLogger)(nil).Infow), varargs...)
}

// MockStreamFileWriter is a mock of StreamFileWriter interface.
type MockStreamFileWriter struct {
	ctrl     *gomock.Controller
	recorder *MockStreamFileWriterMockRecorder
}

// MockStreamFileWriterMockRecorder is the mock recorder for MockStreamFileWriter.
type MockStreamFileWriterMockRecorder struct {
	mock *MockStreamFileWriter
}

// NewMockStreamFileWriter creates a new mock instance.
func NewMockStreamFileWriter(ctrl *gomock.Controller) *MockStreamFileWriter {
	mock := &MockStreamFileWriter{ctrl: ctrl}
	mock.recorder = &MockStreamFileWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamFileWriter) EXPECT() *MockStreamFileWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStreamFileWriter) Close(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStreamFileWriterMockRecorder) Close(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStreamFileWriter)(nil).Close), arg0)
}

// WriteChunk mocks base method.
func (m *MockStreamFileWriter) WriteChunk(arg0 context.Context, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteChunk", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteChunk indicates an expected call of WriteChunk.
func (mr *MockStreamFileWriterMockRecorder) WriteChunk(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteChunk", reflect.TypeOf((*MockStreamFileWriter)(nil).WriteChunk), arg0, arg1, arg2)
}

// MockStreamFileReader is a mock of StreamFileReader interface.
type MockStreamFileReader struct {
	ctrl     *gomock.Controller
	recorder *MockStreamFileReaderMockRecorder
}

// MockStreamFileReaderMockRecorder is the mock recorder for MockStreamFileReader.
type MockStreamFileReaderMockRecorder struct {
	mock *MockStreamFileReader
}

// NewMockStreamFileReader creates a new mock instance.
func NewMockStreamFileReader(ctrl *gomock.Controller) *MockStreamFileReader {
	mock := &MockStreamFileReader{ctrl: ctrl}
	mock.recorder = &MockStreamFileReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamFileReader) EXPECT() *MockStreamFileReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStreamFileReader) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockStreamFileReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStreamFileReader)(nil).Close))
}

// FileSize mocks base method.
func (m *MockStreamFileReader) FileSize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileSize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// FileSize indicates an expected call of FileSize.
func (mr *MockStreamFileReaderMockRecorder) FileSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileSize", reflect.TypeOf((*MockStreamFileReader)(nil).FileSize))
}

// Next mocks base method.
func (m *MockStreamFileReader) Next() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockStreamFileReaderMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockStreamFileReader)(nil).Next))
}
